### ISSUE TITLE
org.bson.BSONException

### ISSUE THREAD

**Issue by agcom** [agcom/bson#12]
In the current implementation, there is a lot of potentials for `org.bson.BSONException` to be thrown.

The end user will only **expect** `kotlinx.serialization.SerializationException`, especially `com.github.agcom.bson.BsonException`.

So, remove that potentials and replace them with the project exclusive exception, `com.github.agcom.bson.BsonException`.

**Comment by Agcom** [comment]
Most potentials are at casting points for primitive types, which `BsonValue` builtin functions are used.

**Comment by agcom** [comment]
Also the `RawBsonValue` uses this exception (future `v1.1.0`).

**Comment by agcom** [comment]
Just gonna use `try/catch` hack for a quick fix.

This issue is auto fixed by `v1.0.0`.
