### ISSUE TITLE
Inferring byte array bson type

### ISSUE THREAD

**Issue by agcom** [agcom/bson#18]
Implementing `load` function needs inferring bson type.

It's not possible to infer bson type in case of `UnionKind.CONTEXTUAL` and `PolymorphicKind` (not `AbstractPolymorphicSerializer`).

So, adding another `load` function which additionally accept a `BsonType`, which is used as the bytes inferred bson type. The original function throws if it can't infer the bson type.

Yet the problem exists in case of more complex serializers which is normal (there is no flag present).

> This is not true in Json, you work with strings there and `{` flags for a Json object. Other than that, literal value is extracted.

**If there be a way to determine if a byte array contains a bson document, the problem is solved**.

_Originally posted by @Agcom in https://github.com/Agcom/bson/issues/6#issuecomment-672814915_

**Comment by Agcom** [comment]
One possible solution is trial and error, optimized by the byte array length.

If there is multiple possible types, both should be returned in body of a `BsonValue` (possible by creating a custom subclass).

**Comment by Agcom** [comment]
More specific, the problem arises only when we're trying to load a `BsonValue`, not knowing what type it's gonna be.

Also, relying on `SerialKind`'s leaf classes, is not a good choice. Maybe Kotlinx serialization library isn't flexible enough.
> A good example for this is, `ObjectIdSerializer`. It's serial kind is `PrimitiveKind.STRING`, but writes / reads an object id.

**Comment by Agcom** [comment]
So, only `StructureKind` and `PolymorphicKind` with `AbstractPolymorphicSerializer` are safe to infer the bson type from.

**Comment by agcom** [comment]
**Abandoning** this issue.

Although it made possible by `RawBsonValue`, it adds extra cognitive load and more code complexity.

Better to just follow the bson specification.
