### ISSUE TITLE
Refactor internal structures

### ISSUE THREAD

**Issue by agcom** [agcom/bson#20]
- [x] Move main module into a sub-module called `core`
- [x] Code documentations.
- [x] Change internal package structure
- [x] Clean and group the tests + ~extend the tests~
- [x] Move maven artifact pom configuration, to a file `pom.xml`.
- [x] Serializers **serialName**:
`Custom serializers should provide a unique serial name that identify both the serializable class and the serializer itself, ignoring type arguments, if they are present.`
- [x] Default bson context tests (that it won't break)
- [x] `TemporalSerializer` tests (so there is no code typo on porting to each others)
- [x] Create `unexpected bson type` universal exception
- [x] Special serializers tests

**Comment by Agcom** [comment]
#17

**Comment by Agcom** [comment]
#17

**Comment by Agcom** [comment]
`SerializationCodecRegistryTest` cleaned and extended.

**Comment by agcom** [comment]
- `Custom serializers should provide a unique serial name that identify both the serializable class and the serializer itself, ignoring type arguments, if they are present.`

**Comment by agcom** [comment]
- [ ] Default bson context tests (that it won't break)
- [ ] `TemporalSerializer` tests (so there is no code typo on porting to each others)
- [ ] Create unexpected bson type universal exception

**Comment by agcom** [comment]
Not gonna extend the tests, because this are all gonna be obsolete codes after `v2`.

**Comment by agcom** [comment]
- [ ] Special serializers tests
